/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EasyBet__factory } from "./EasyBet__factory";
export { EasyBetToken__factory } from "./EasyBetToken__factory";
